Mytask/Mytask/Models/AddUser.cs
namespace Mytask.Models
{
    public class AddUser
    {

        public Guid Id { get; set; }

        public int UserId { get; set; }
        public string Name { get; set; }    
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address {  get; set; }    

        public long Salary {  get; set; }
        public DateTime CreatedDate { get; set;}
        public string Department {  get; set; }
        public string Description { get; set; }
      
        


   
    }
}

Mytask/Mytask/Models/ErrorViewModel.cs
namespace Mytask.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mytask/Mytask/Models/UpdateUser.cs
namespace Mytask.Models
{
    public class UpdateUser
    {
        public Guid Id { get; set; }

        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }

        public long Salary { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Department { get; set; }
        public string Description { get; set; }
    }
}

Mytask/Mytask/Models/User.cs
namespace Mytask.Models
{
    public class User
    {
        public Guid Id { get; set; }

        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }

        public long Salary { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Department { get; set; }
        public string Description { get; set; }
    }
}

Mytask/Mytask/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Mytask.Models;
using System.Diagnostics;

namespace Mytask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mytask/Mytask/Controllers/MyUserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mytask.Data;
using Mytask.Models;

namespace Mytask.Controllers
{
    public class MyUserController : Controller
    {

        private readonly MyDBContext context1;

        public MyUserController(MyDBContext demoDbContext)
        {
            this.context1= demoDbContext;
        }

        [HttpGet]

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult>Add(AddUser u)
        {
            var user1 = new User()
            {
                Id = Guid.NewGuid(),
                UserId = u.UserId,
                Name = u.Name,
                Email = u.Email,
                Phone = u.Phone,
                Address = u.Address,
                Salary = u.Salary,
                CreatedDate = u.CreatedDate,
                Department = u.Department,
                Description = u.Description

            };

            await context1.Users.AddAsync(user1);
            await context1.SaveChangesAsync();
            return RedirectToAction("Add");
        }





        public async Task<IActionResult> Index()
        {

            var u1 = await context1.Users.ToListAsync();
            return View(u1);
        }

        [HttpGet]
        public IActionResult DisplayById()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult>DisplayById(int uid,string sub)
        {
            if(sub=="Display")
            {
                var userdata=await context1.Users.FirstOrDefaultAsync(x=>x.UserId==uid);
                return View(userdata);
            }
            else if(sub=="Delete")
            {
                var userdata= await context1.Users.FirstOrDefaultAsync(x=> x.UserId==uid);
                if(userdata!=null)
                {
                    context1.Users.Remove(userdata);
                    await context1.SaveChangesAsync();
                    return RedirectToAction("DisplayById");
                }
                return View();
            }
            else
            {
                var userdata = await context1.Users.FirstOrDefaultAsync(x => x.UserId==uid);
                var u = new UpdateUser()
                {
                    Id = userdata.Id,
                    UserId = userdata.UserId,
                    Name = userdata.Name,
                    Email = userdata.Email,
                    Phone = userdata.Phone,
                    Address = userdata.Address,
                    Salary = userdata.Salary,
                    CreatedDate = userdata.CreatedDate,
                    Department = userdata.Department,
                    Description = userdata.Description

                };

                return View("Edit",u);



            }
        }


        public async Task<IActionResult>Update(UpdateUser u)
        {

            var user=await context1.Users.FirstOrDefaultAsync(x=>x.UserId==u.UserId);
            if(user!=null) 
            { 
                user.Name= u.Name;
                user.Email= u.Email;
                user.Phone= u.Phone;
                user.Address= u.Address;
                user.Salary= u.Salary;
                user.CreatedDate = u.CreatedDate;
                user.Department= u.Department;
                user.Description= u.Description;
                await context1.SaveChangesAsync();
                return RedirectToAction("DisplayById");
            }
            return View("DisplayById");
        }


        [HttpGet]

        public async Task<IActionResult>A_Delete(int id)
        {

            var userdata=await context1.Users.FirstOrDefaultAsync(x=>x.UserId == id);
            if(userdata!=null)
            {
                context1.Users.Remove(userdata);
                await context1.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }



        [HttpGet]
        public async Task<IActionResult>A_Edit(int id)
        {
            var userdata = await context1.Users.FirstOrDefaultAsync(x => x.UserId == id);
            var u = new UpdateUser()
            {
                UserId = userdata.UserId,
                Name = userdata.Name,
                Email = userdata.Email,
                Phone = userdata.Phone,

                Address = userdata.Address,
                Salary = userdata.Salary,
                CreatedDate = userdata.CreatedDate,
                Department = userdata.Department




            };
            return await Task.Run(() => View("Edit", u));
        }


        [HttpPost]
        public async Task<IActionResult>A_Edit(UpdateUser u)
        {
            var user=await context1.Users.FirstOrDefaultAsync(x=>x.UserId == u.UserId);
            if(user!=null) 
            { 
                user.Name= u.Name;  
                user.Email= u.Email;
                user.Phone= u.Phone;
                user.Address= u.Address;
                    
                user.Salary= u.Salary;
                user.CreatedDate = u.CreatedDate;
                user.Department = u.Department;
                await context1.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
         
      

     
    }
}

Mytask/Mytask/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h2>User Information</h2>
</div>

Mytask/Mytask/Views/MyUser/A_Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Mytask.Models.UpdateUser;

<form method="post" action="A_Edit">
    <div class="mb-3">
        // <label class="form-label">UserId</label>
        <input type="hidden" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="UserId">
        <span id="msg1" class="text-danger"></span>
    </div>


    <div class="mb-3">
        <label class="form-label">Name</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Name">

    </div>


    <div class="mb-3">
        <label class="form-label">Email</label>

        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Email">
    </div>



    <div class="mb-3">
        <label class="form-label">Phone</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Phone">

    </div>



    <div class="mb-3">
        <label class="form-label">Address</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Address">

    </div>



    <div class="mb-3">
        <label class="form-label">Salary</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Salary">

    </div>



    <div class="mb-3">
        <label class="form-label">CreatedDate</label>
        <input type="date" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="CreatedDate">

    </div>


    <div class="mb-3">
        <label class="form-label">Department</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Department">

    </div>



    <div class="mb-3">
        <label class="form-label">Description</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Description">

    </div>


    <button type="submit" class="btn btn-primary">Update</button>



</form>

Mytask/Mytask/Views/MyUser/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Mytask.Models.AddUser;
<form method="post" action="Add">
    <div class="mb-3">
        <label class="form-label">UserId</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="UserId">
        <span id="msg1" class="text-danger"></span>
    </div>


    <div class="mb-3">
        <label class="form-label">Name</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Name">
        
    </div>


    <div class="mb-3">
        <label class="form-label">Email</label>

        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Email">
    </div>



    <div class="mb-3">
        <label class="form-label">Phone</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Phone">

    </div>



    <div class="mb-3">
        <label class="form-label">Address</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Address">

    </div>



    <div class="mb-3">
        <label class="form-label">Salary</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Salary">

    </div>



    <div class="mb-3">
        <label class="form-label">CreatedDate</label>
        <input type="date" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="CreatedDate">

    </div>


    <div class="mb-3">
        <label class="form-label">Department</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Department">

    </div>



    <div class="mb-3">
        <label class="form-label">Description</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Description">

    </div>


    <button type="submit" class="btn btn-primary">Submit</button>



</form>

Mytask/Mytask/Views/MyUser/DisplayById.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Mytask.Models.User;

<div class="container">
<form method="post" action="DisplayById">
    <div class="mb-3">
        <label class="form-label">UserId</label>
            <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" name="uid">
            <br />
            <input type="submit" name="sub" value="Display" class="btn btn-danger"/>
            <input type="submit" name="sub" value="Delete" class="btn btn-danger" />
            <input type="submit" name="sub" value="Edit" class="btn btn-danger" />
    </div>


</form>
</div>

<div class="container">
    <table class="table table hover">
        <tr>
            
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Salary</th>
            <th>Date</th>
            <th>Department</th>
            <th>Description</th>
        </tr>
        @{
            if (Model!=null)
            {
                <tr>
                    <td>@Model.UserId</td>
                    <td>@Model.Name</td>
                    <td>@Model.Email</td>
                    <td>@Model.Phone</td>
                    <td>@Model.Address</td>
                    <td>@Model.Salary</td>
                    <td>@Model.CreatedDate</td>
                    <td>@Model.Department</td>
                    <td>@Model.Description</td>

                </tr>
            }
        }

    </table>
</div>

Mytask/Mytask/Views/MyUser/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Mytask.Models.UpdateUser;

<form method="post" action="Update">
    <div class="mb-3">
       // <label class="form-label">UserId</label>
        <input type="hidden" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="UserId">
        <span id="msg1" class="text-danger"></span>
    </div>


    <div class="mb-3">
        <label class="form-label">Name</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Name">

    </div>


    <div class="mb-3">
        <label class="form-label">Email</label>

        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Email">
    </div>



    <div class="mb-3">
        <label class="form-label">Phone</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Phone">

    </div>



    <div class="mb-3">
        <label class="form-label">Address</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Address">

    </div>



    <div class="mb-3">
        <label class="form-label">Salary</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Salary">

    </div>



    <div class="mb-3">
        <label class="form-label">CreatedDate</label>
        <input type="date" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="CreatedDate">

    </div>


    <div class="mb-3">
        <label class="form-label">Department</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Department">

    </div>



    <div class="mb-3">
        <label class="form-label">Description</label>
        <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" asp-for="Description">

    </div>


    <button type="submit" class="btn btn-primary">Update</button>



</form>

Mytask/Mytask/Views/MyUser/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Mytask.Models.User>
<div class="container">
    <table class="table table-hover">
        <tr>
           <th>ID</th>
           <th>Name</th>
           <th>Email</th>
           <th>Phone</th>
           <th>Address</th>
           <th>Salary</th>
           <th>Date</th>
           <th>Department</th>
           <th>Description</th>
        </tr>
        @{
            foreach(var u in Model)
            {
                <tr>
                <td>@u.UserId</td>
                <td>@u.Name</td>
                <td>@u.Email</td>
                <td>@u.Phone</td>
                <td>@u.Address</td>
                <td>@u.Salary</td>
                <td>@u.CreatedDate</td>
                <td>@u.Department</td>
                <td>@u.Description</td>
                    <td>
                        <a class="btn btn-danger" href="A_Delete/@u.UserId">Delete</a>
                        <a class="btn btn-danger" href="A_Edit/@u.UserId">Edit</a>
                    </td>
                </tr>
            }

        }
        


    </table>

</div>

Mytask/Mytask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mytask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mytask.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/mystyle.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mytask</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyUser" asp-action="Add">AddUser</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyUser" asp-action="Index">UserInfo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyUser" asp-action="DisplayById">Modification</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Mytask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>